name: 'e2e_lakehouse'
version: '1.0'
config-version: 2
profile: 'dbt_lakehouse'

models:
  e2e_lakehouse:
    staging:
      +materialized: table
      +schema: silver
      +file_format: iceberg
    marts:
      +schema: analytics
