e2e_lakehouse:
  outputs:
    dev:
      type: postgres
      host: northwind-db
      user: admin
      password: admin
      port: 5432
      dbname: northwind
      schema: public

    thrift:
      type: spark
      method: thrift
      host: spark-thrift-server
      port: 10000
      schema: default

  # Default target set to the Spark Thrift Server for transformation runs
  target: thrift
