version: 2

sources:
  - name: bronze
    schema: bronze
    tables:
      - name: orders
      - name: customers
      - name: products
      - name: order_details

models:
  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null

  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: stg_order_details
    columns:
      - name: order_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null